# Site Settings
title:               Saurav Singh
tagline:             damngamerz
github:
author:
  name:              "Saurav Singh"
  email:             "sauravsinghshakya@yahoo.com"
  twitter:           "damngamerz"
  instagram:         "damngamerz"
  github:            "damngamerz"
  facebook:          "damngamerz"
  linkedin:          "saurav-singh"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]

#Feed settings
name:                Saurav Singh
description:         Personal Blog
url:                 http://www.damngamerz.github.io
