# Site Settings
title:               Saurav Singh
tagline:             damngamerz
description:
url:                #"https://damngamerz.github.io"
github:
  url:               "https://damngamerz.github.io"
author:
  name:              "Saurav Singh"
  email:             "sauravsinghshakya@yahoo.com"
  twitter:           "damngamerz"
  instagram:         "damngamerz"
  github:            "damngamerz"
  facebook:          "damngamerz"
  linkedin:          "saurav-singh"
paginate:            5
disqus:              "your-disqus"


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]

#Feed settings
name:                Saurav Singh
description:         Personal Blog
url:                 https://damngamerz.github.io
