# Site Settings
title:               Saurav Singh
tagline:             damngamerz
description:
url:                 "https://saurav.eu"
github:
  url:               "https://damngamerz.github.io"
author:
  name:              "Saurav Singh"
  email:             "sauravsinghshakya@yahoo.com"
  twitter:           "damngamerz"
  instagram:         "damngamerz"
  github:            "damngamerz"
  facebook:          "damngamerz"
  linkedin:          "damngamerz"
  rss:               "feed.xml"
  gitlab:            "damngamerz"
paginate:            5
disqus:              "damngamerz"


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]

#Feed settings
name:                Saurav Singh
description:         Personal Blog
url:                 https://damngamerz.github.io
